### ISSUE TITLE
Clarification of mirror and lens size requirements

### ISSUE THREAD

**Issue by BarnumD** [nortd/lasersaur#12]
Pages like this (https://github.com/nortd/lasersaur/wiki/operation) and (http://store.lasersaur.com/index.php?route=product/product&path=59&product_id=67&currency=USD) mention 25mm.  However, some of the links go to products that are 25mm, some go to products that are 20mm, and some to old ebay pages that don't provide that information.

Can you please clarify if the mirrors AND/OR the lenses must be 25mm or if some other size is acceptable?  Thank You.

**Comment by stefanix** [comment]
info on page, thx
